### PR TITLE
added last update date next to api version

### PR DESCRIPTION
**Pull request by janfriedli**
EVO-403

### CODE REVIEW

**Comment by janfriedli** [comment]
@hairmare any idea why the travis check failed?

**Comment by hairmare** [comment]
It always does... I've started a more sane approach in http://swagger-browser-develop.nova.scapp.io/ but haven't finished the integration in local deploys yet for that...

Could you also point me in the direction of the code that is writing the info.lastUpdate field? I'd like to see where that's coming from...

**Comment by hairmare** [comment]
Also, I can't seem to see this reflected in the [EVO 403 story](https://issue.swisscom.ch/browse/EVO-403)...

**Comment by janfriedli** [comment]
It's related to this [PR](https://github.com/libgraviton/graviton/pull/260). 
The "last update" field is generated when running swagger:generate so the swagger-ui fetches the date from swagger.json 
[see here](https://github.com/libgraviton/graviton/compare/feature/swagger-version-numbers#diff-f1c21e4a26ea6e87da6e9637339b5ed2R186)

**Pull request closed without merging**
